In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv ('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [3]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [4]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [5]:
#creating arrays 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(2)

array([1., 1.])

In [7]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
#convert list to arrayh
a=np.array([1,2,3,4,5])

In [9]:
#access element 3
a[2]

np.int64(3)

In [10]:
#access element 3
a[2] =10

In [11]:
#access element 3
a[2]

np.int64(10)

In [12]:
#I want values 0,1,3,4,...,9 not 10!!! it is 10 non inclusive
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#I want values 3,4,...,9 
np.arange(3,10) 

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
#FILL WITH NUMBERS FROM 0,1 OF SIZE 11 AND IT FILLS EVERYTHING IN BETWEEN THOSE WITH THAT SIZE SPLIT
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [15]:
#notice the odd steps are prettier than even because it is 
# inclusive of the starting element which in this case is zero
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [16]:
#multidimensional arrays
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
#multidimensional arrays
"""
np.array([
       _0,1,2_
   _0_ [1,2,3],
   _1_ [3,4,5],
   _2_ [4,7,8]
])
"""
n=np.array([
    [1,2,3],
    [3,4,5],
    [4,7,8]
])

In [18]:
n[0,1]

np.int64(2)

In [19]:
n[0,1]=40000

In [20]:
n

array([[    1, 40000,     3],
       [    3,     4,     5],
       [    4,     7,     8]])

In [21]:
# accessing first row
n[0]

array([    1, 40000,     3])

In [22]:
n[2]=[1,np.pi,0.00000001]

In [23]:
n

array([[    1, 40000,     3],
       [    3,     4,     5],
       [    1,     3,     0]])

In [24]:
# accessing first colo
n[:,2]

array([3, 5, 0])

In [25]:
# accessing first colo
n[:,2]=[9,9,9]
n

array([[    1, 40000,     9],
       [    3,     4,     9],
       [    1,     3,     9]])

In [26]:
# accessing first kolo
n[:,2]=99999999999
n[:,2]

array([99999999999, 99999999999, 99999999999])

In [27]:
n

array([[          1,       40000, 99999999999],
       [          3,           4, 99999999999],
       [          1,           3, 99999999999]])

In [28]:
n[:]

array([[          1,       40000, 99999999999],
       [          3,           4, 99999999999],
       [          1,           3, 99999999999]])

In [29]:
# randomly generated arr 5rows and 2kolous std uni dissss
np.random.seed(42)
np.random.rand(5,2)

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615],
       [0.60111501, 0.70807258]])

In [30]:
np.random.seed(42)
np.random.rand(5,2)

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615],
       [0.60111501, 0.70807258]])

In [31]:
#standard normal distro is similar but with randn
np.random.randn(5,2)

array([[-0.46947439,  0.54256004],
       [-0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024],
       [-1.72491783, -0.56228753],
       [-1.01283112,  0.31424733]])

In [32]:
#if you want numbers between 100 you just multiply every element by 100
100.*np.random.rand(5,2)

array([[29.21446485, 36.63618433],
       [45.60699842, 78.51759614],
       [19.96737822, 51.42344384],
       [59.24145689,  4.64504127],
       [60.75448519, 17.05241237]])

In [33]:
#or you can spetsify lowest and highest manual
np.random.randint(low=0, high=100,size=(5,2))

array([[38, 17],
       [ 3, 88],
       [59, 13],
       [ 8, 89],
       [52,  1]])

In [34]:
#element wise operations
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [35]:
b = (10+(a*2))**2/100

In [36]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [37]:
a+b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [38]:
a/b

array([0.        , 0.69444444, 1.02040816, 1.171875  , 1.2345679 ])

In [39]:
# comparison opera
a>=2

array([False, False,  True,  True,  True])

In [40]:
a>b

array([False, False,  True,  True,  True])

In [41]:
# to find elements greater within the array, suggestive of where it comes from in pandas
a[a>b]

array([2, 3, 4])

In [42]:
#summarizing operat
a.sum()

np.int64(10)

In [43]:
a.mean()

np.float64(2.0)

In [44]:
a.min()

np.int64(0)

In [45]:
a.std()

np.float64(1.4142135623730951)

In [46]:
u=np.array([2,4,5,6])
v=np.array([1,0,0,2])

In [47]:
#vector vector multiplication dot prod or inner prod

def vector_vector_multiplication(a, b):
    assert a.shape[0] == b.shape[0] #same size and the zero is for just the number not a dtype
    n=b.shape[0]
    result = 0.0
    for i in range(n):
        result = result + a[i]*b[i]

    return result

In [48]:
#test this 
vector_vector_multiplication(u, v)

np.float64(14.0)

In [49]:
# this already exists in numpy so we can directly use 
u.dot(v)

np.int64(14)

In [50]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

In [51]:
v

array([1, 0, 0, 2])

In [52]:
# vectro mtrx mult
def matrix_vector_multiplication(A,b):
    assert A.shape[1] == b.shape[0]
    num_rows = A.shape[0]
    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(A[i],b)
    return result    

In [53]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [54]:
U.dot(v)

array([14,  5,  5])

In [55]:
V=np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])

In [56]:
# mtrx mtrx mult
def matrix_matrix_multiplication(A,B):
    assert A.shape[1] == B.shape[0]
    num_rows = A.shape[0]
    num_cols = B.shape[1]
    result = np.zeros((num_rows, num_cols))
    for i in range(num_cols):
        bi=B[:, i]
        Abi = matrix_vector_multiplication(A,bi)
        result[:, i] = Abi
    return result    

In [57]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [58]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [59]:
# identit matrx
I=np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [61]:
#computing the inverse, lets grab the first three rows of our matreix so it is square
Vs = V[[0,1,2]]

In [62]:
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [63]:
Vs_inv = np.linalg.inv(Vs)

In [64]:
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [65]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
#this will be useful for linear regression we will see later.

In [67]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [68]:
df = pd.DataFrame(data, columns=columns)

In [69]:
df 

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [70]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [71]:
df['Make']

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [72]:
#put a list inside brackets
df[['Make', 'Model', 'MSRP']]

Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

In [73]:
# add another column called id
df['id'] = [1, 2, 3, 4, 5]

In [74]:
df['id']

0    1
1    2
2    3
3    4
4    5
Name: id, dtype: int64

In [75]:
df['id'] = [10, 20, 30, 40, 50]

In [76]:
# similar to dict we can use del oprator to delete a kolo
del df['id']

In [77]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [78]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [79]:
df.Make.index

RangeIndex(start=0, stop=5, step=1)

In [80]:
df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [81]:
df.loc[[1,2]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
1         Sedan  27150  
2   convertible  54990

In [82]:
# replace the index for example
df.index = ['a' ,'b' ,'c', 'd', 'e']

In [83]:
#  this s'pos'ta err out cuz we switched da index to abcde 
# df.loc[[1,2]]

"""
OUTPUT

Skip to Main
df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 1, dtype: object

df.loc[[1,2]]
	Make 	Model 	Year 	Engine HP 	Engine Cylinders 	Transmission Type 	Vehicle_Style 	MSRP
1 	Hyundai 	Sonata 	2017 	NaN 	4 	AUTOMATIC 	Sedan 	27150
2 	Lotus 	Elise 	2010 	218.0 	4 	MANUAL 	convertible 	54990
# replace the index for example
df.index = ['a' ,'b' ,'c', 'd', 'e']
#  this s'pos'ta err out cuz we switched da index to abcde 
df.loc[[1,2]]

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[83], line 2
      1 #  this s'pos'ta err out cuz we switched da index to abcde 
----> 2 df.loc[[1,2]]

File ~/.local/lib/python3.12/site-packages/pandas/core/indexing.py:1191, in _LocationIndexer.__getitem__(self, key)
   1189 maybe_callable = com.apply_if_callable(key, self.obj)
   1190 maybe_callable = self._check_deprecated_callable_usage(key, maybe_callable)
-> 1191 return self._getitem_axis(maybe_callable, axis=axis)

File ~/.local/lib/python3.12/site-packages/pandas/core/indexing.py:1420, in _LocIndexer._getitem_axis(self, key, axis)
   1417     if hasattr(key, "ndim") and key.ndim > 1:
   1418         raise ValueError("Cannot index with multidimensional key")
-> 1420     return self._getitem_iterable(key, axis=axis)
   1422 # nested tuple slicing
   1423 if is_nested_tuple(key, labels):

File ~/.local/lib/python3.12/site-packages/pandas/core/indexing.py:1360, in _LocIndexer._getitem_iterable(self, key, axis)
   1357 self._validate_key(key, axis)
   1359 # A collection of keys
-> 1360 keyarr, indexer = self._get_listlike_indexer(key, axis)
   1361 return self.obj._reindex_with_indexers(
   1362     {axis: [keyarr, indexer]}, copy=True, allow_dups=True
   1363 )

File ~/.local/lib/python3.12/site-packages/pandas/core/indexing.py:1558, in _LocIndexer._get_listlike_indexer(self, key, axis)
   1555 ax = self.obj._get_axis(axis)
   1556 axis_name = self.obj._get_axis_name(axis)
-> 1558 keyarr, indexer = ax._get_indexer_strict(key, axis_name)
   1560 return keyarr, indexer

File ~/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py:6212, in Index._get_indexer_strict(self, key, axis_name)
   6209 else:
   6210     keyarr, indexer, new_indexer = self._reindex_non_unique(keyarr)
-> 6212 self._raise_if_missing(keyarr, indexer, axis_name)
   6214 keyarr = self.take(indexer)
   6215 if isinstance(key, Index):
   6216     # GH 42790 - Preserve name from an Index

File ~/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py:6261, in Index._raise_if_missing(self, key, indexer, axis_name)
   6259 if nmissing:
   6260     if nmissing == len(indexer):
-> 6261         raise KeyError(f"None of [{key}] are in the [{axis_name}]")
   6263     not_found = list(ensure_index(key)[missing_mask.nonzero()[0]].unique())
   6264     raise KeyError(f"{not_found} not in index")

KeyError: "None of [Index([1, 2], dtype='int64')] are in the [index]"
"""

'\nOUTPUT\n\nSkip to Main\ndf.loc[1]\n\nMake                   Hyundai\nModel                   Sonata\nYear                      2017\nEngine HP                  NaN\nEngine Cylinders             4\nTransmission Type    AUTOMATIC\nVehicle_Style            Sedan\nMSRP                     27150\nName: 1, dtype: object\n\ndf.loc[[1,2]]\n\tMake \tModel \tYear \tEngine HP \tEngine Cylinders \tTransmission Type \tVehicle_Style \tMSRP\n1 \tHyundai \tSonata \t2017 \tNaN \t4 \tAUTOMATIC \tSedan \t27150\n2 \tLotus \tElise \t2010 \t218.0 \t4 \tMANUAL \tconvertible \t54990\n# replace the index for example\ndf.index = [\'a\' ,\'b\' ,\'c\', \'d\', \'e\']\n#  this s\'pos\'ta err out cuz we switched da index to abcde \ndf.loc[[1,2]]\n\n---------------------------------------------------------------------------\nKeyError                                  Traceback (most recent call last)\nCell In[83], line 2\n      1 #  this s\'pos\'ta err out cuz we switched da index to abcde \n----> 2 df.loc[[1,2]]\n

In [84]:
df.loc[['b', 'e']]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
b         Sedan  27150  
e        Pickup  32340

In [85]:
# we can refer to a positinal index but sted of loc we do iloc and we still look for exactly the elements
df.iloc[[1, 2]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
b  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
b         Sedan  27150  
c   convertible  54990

In [86]:
# come back to our trad index in our table for our index but it keeps the old index
df.reset_index()

index     Make     Model  Year  Engine HP  Engine Cylinders  \
0     a   Nissan    Stanza  1991      138.0                 4   
1     b  Hyundai    Sonata  2017        NaN                 4   
2     c    Lotus     Elise  2010      218.0                 4   
3     d      GMC    Acadia  2017      194.0                 4   
4     e   Nissan  Frontier  2017      261.0                 6   

  Transmission Type Vehicle_Style   MSRP  
0            MANUAL         sedan   2000  
1         AUTOMATIC         Sedan  27150  
2            MANUAL   convertible  54990  
3         AUTOMATIC       4dr SUV  34450  
4            MANUAL        Pickup  32340

In [87]:
# notice it kept both indices, if we dont care for the abcde one just drop true it
df.reset_index(drop=True)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [88]:
# BE CAREFUL IT DIDNT CHANGE DF!!!!! (think deep vs shallow copy and all that jazz)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            MANUAL   
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   convertible  54990  
d       4dr SUV  34450  
e        Pickup  32340

In [89]:
# reassign to df to do that
df = df.reset_index(drop=True)

In [90]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [91]:
#element wise operations we can apply an operations to all element of array similar to numpy
df['Engine HP']/100

0    1.38
1     NaN
2    2.18
3    1.94
4    2.61
Name: Engine HP, dtype: float64

In [92]:
#element wise operations we can apply an operations to all element of array similar to numpy
df['Engine HP']*100

0    13800.0
1        NaN
2    21800.0
3    19400.0
4    26100.0
Name: Engine HP, dtype: float64

In [93]:
# FILTERING
# like numpy we have some logic oper, find all records after 2015
df['Year']>= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

In [94]:
# FILTERING
# now give me all fields in df of cars that that were 
# manufactured post 2015 including. So it looks at the true abvove and returns those in the df
df[
    df['Year']>= 2015
]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
1         Sedan  27150  
3       4dr SUV  34450  
4        Pickup  32340

In [95]:
# FILTERING
# now give me all fields in df of cars that that were made by nissan
df[
    df['Make']== 'Nissan'
]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0  Nissan    Stanza  1991      138.0                 4            MANUAL   
4  Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
4        Pickup  32340

In [96]:
# FILTERING
# now give me all fields in df of cars that that were 
# manufactured post 2015 including and were made by nissan
df[
    ( df['Year']>= 2015 ) & ( df['Make']== 'Nissan' )
]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
4  Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
4        Pickup  32340

In [97]:
# in python in general there exists a method called lower that makes things small
'STR'.lower()

'str'

In [98]:
# if you want to replace all ocurr of space with undersc you use replace of string
'machine learning zoomcamp'.replace(' ','_')

'machine_learning_zoomcamp'

In [99]:
# string oper, not in numpy 
df['Vehicle_Style']

0          sedan
1          Sedan
2    convertible
3        4dr SUV
4         Pickup
Name: Vehicle_Style, dtype: object

In [100]:
# in python in general there exists a method called lower that makes things small
df['Vehicle_Style'].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: object

In [101]:
# in python in general there exists a method called lower that makes things small
# notice that it doesnt change this but returns a new series and as such we lose the lower cmd from above
# so we will chain it on the next cell
df['Vehicle_Style'].str.replace(' ','_')

0          sedan
1          Sedan
2    convertible
3        4dr_SUV
4         Pickup
Name: Vehicle_Style, dtype: object

In [102]:
# chain it on this cell
df['Vehicle_Style'].str.lower().str.replace(' ','_')

0          sedan
1          sedan
2    convertible
3        4dr_suv
4         pickup
Name: Vehicle_Style, dtype: object

In [103]:
# use assignement operator to do a deep assignment (my terminology lol)
df['Vehicle_Style'] = df['Vehicle_Style'].str.lower().str.replace(' ','_')

In [104]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         sedan  27150  
2   convertible  54990  
3       4dr_suv  34450  
4        pickup  32340

In [105]:
# summarizing operators, same as numpy
df.MSRP.min()

np.int64(2000)

In [106]:
# summarizing operators, same as numpy
df.MSRP.max()

np.int64(54990)

In [107]:
# summarizing operators, same as numpy
df.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [108]:
# for whole df, autofinds all numeric kolous and gives you those description for them.
df.describe()

Year  Engine HP  Engine Cylinders          MSRP
count     5.000000    4.00000          5.000000      5.000000
mean   2010.400000  202.75000          4.400000  30186.000000
std      11.260551   51.29896          0.894427  18985.044904
min    1991.000000  138.00000          4.000000   2000.000000
25%    2010.000000  180.00000          4.000000  27150.000000
50%    2017.000000  206.00000          4.000000  32340.000000
75%    2017.000000  228.75000          4.000000  34450.000000
max    2017.000000  261.00000          6.000000  54990.000000

In [112]:
# calc how meny uniq values are there we use the noonik operatair
df.Make.nunique()

4

In [114]:
# we can apply to the whole thing if you want want, there are 4 unique values for make , 5 for model....
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
dtype: int64

In [116]:
# want to know how many nans theyt are and deal with them, but not super usefull though
df.isnull()

Make  Model   Year  Engine HP  Engine Cylinders  Transmission Type  \
0  False  False  False      False             False              False   
1  False  False  False       True             False              False   
2  False  False  False      False             False              False   
3  False  False  False      False             False              False   
4  False  False  False      False             False              False   

   Vehicle_Style   MSRP  
0          False  False  
1          False  False  
2          False  False  
3          False  False  
4          False  False

In [117]:
# ciombiner with sum to get how many nanananana there are | Engine HP...1 | in this case
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

We want to group price by transmission type and then compute the average number
```
select
    transmission_type,
    AVG(MSRP)
from
    cars
group by
    transmission_type
```

In [119]:
df.groupby('Transmission Type').MSRP.mean()

Transmission Type
AUTOMATIC    30800.000000
MANUAL       29776.666667
Name: MSRP, dtype: float64

In [123]:
# casted to int32 so it matches video and to learn casting
df.groupby('Transmission Type').MSRP.mean().astype('int32')

Transmission Type
AUTOMATIC    30800
MANUAL       29776
Name: MSRP, dtype: int32

In [120]:
# to grab underly numpee arr we use .values
df.MSRP.values

array([ 2000, 27150, 54990, 34450, 32340])

In [125]:
# converting back to a list of dics and do this per record using orient
df.to_dict(orient='records')

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr_suv',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'pickup',
  'MSRP': 32340}]