In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv ('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [3]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [4]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [5]:
#creating arrays 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(2)

array([1., 1.])

In [7]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
#convert list to arrayh
a=np.array([1,2,3,4,5])

In [9]:
#access element 3
a[2]

np.int64(3)

In [10]:
#access element 3
a[2] =10

In [11]:
#access element 3
a[2]

np.int64(10)

In [12]:
#I want values 0,1,3,4,...,9 not 10!!! it is 10 non inclusive
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#I want values 3,4,...,9 
np.arange(3,10) 

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
#FILL WITH NUMBERS FROM 0,1 OF SIZE 11 AND IT FILLS EVERYTHING IN BETWEEN THOSE WITH THAT SIZE SPLIT
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [15]:
#notice the odd steps are prettier than even because it is 
# inclusive of the starting element which in this case is zero
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [16]:
#multidimensional arrays
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
#multidimensional arrays
"""
np.array([
       _0,1,2_
   _0_ [1,2,3],
   _1_ [3,4,5],
   _2_ [4,7,8]
])
"""
n=np.array([
    [1,2,3],
    [3,4,5],
    [4,7,8]
])

In [18]:
n[0,1]

np.int64(2)

In [19]:
n[0,1]=40000

In [20]:
n

array([[    1, 40000,     3],
       [    3,     4,     5],
       [    4,     7,     8]])

In [21]:
# accessing first row
n[0]

array([    1, 40000,     3])

In [22]:
n[2]=[1,np.pi,0.00000001]

In [23]:
n

array([[    1, 40000,     3],
       [    3,     4,     5],
       [    1,     3,     0]])

In [24]:
# accessing first colo
n[:,2]

array([3, 5, 0])

In [25]:
# accessing first colo
n[:,2]=[9,9,9]
n

array([[    1, 40000,     9],
       [    3,     4,     9],
       [    1,     3,     9]])

In [26]:
# accessing first kolo
n[:,2]=99999999999
n[:,2]

array([99999999999, 99999999999, 99999999999])

In [27]:
n

array([[          1,       40000, 99999999999],
       [          3,           4, 99999999999],
       [          1,           3, 99999999999]])

In [28]:
n[:]

array([[          1,       40000, 99999999999],
       [          3,           4, 99999999999],
       [          1,           3, 99999999999]])

In [29]:
# randomly generated arr 5rows and 2kolous std uni dissss
np.random.seed(42)
np.random.rand(5,2)

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615],
       [0.60111501, 0.70807258]])

In [30]:
np.random.seed(42)
np.random.rand(5,2)

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615],
       [0.60111501, 0.70807258]])

In [32]:
#standard normal distro is similar but with randn
np.random.randn(5,2)

array([[-0.46947439,  0.54256004],
       [-0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024],
       [-1.72491783, -0.56228753],
       [-1.01283112,  0.31424733]])

In [33]:
#if you want numbers between 100 you just multiply every element by 100
100.*np.random.rand(5,2)

array([[29.21446485, 36.63618433],
       [45.60699842, 78.51759614],
       [19.96737822, 51.42344384],
       [59.24145689,  4.64504127],
       [60.75448519, 17.05241237]])

In [35]:
#or you can spetsify lowest and highest manual
np.random.randint(low=0, high=100,size=(5,2))

array([[38, 17],
       [ 3, 88],
       [59, 13],
       [ 8, 89],
       [52,  1]])

In [36]:
#element wise operations
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [39]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [37]:
b = (10+(a*2))**2/100

In [38]:
a+b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [40]:
a/b

array([0.        , 0.69444444, 1.02040816, 1.171875  , 1.2345679 ])

In [41]:
# comparison opera
a>=2

array([False, False,  True,  True,  True])

In [42]:
a>b

array([False, False,  True,  True,  True])

In [43]:
# to find elements greater within the array, suggestive of where it comes from in pandas
a[a>b]

array([2, 3, 4])

In [44]:
#summarizing operat
a.sum()

np.int64(10)

In [45]:
a.mean()

np.float64(2.0)

In [46]:
a.min()

np.int64(0)

In [47]:
a.std()

np.float64(1.4142135623730951)

In [49]:
u=np.array([2,4,5,6])
v=np.array([1,0,0,2])

In [74]:
#vector vector multiplication dot prod or inner prod

def vector_vector_multiplication(a, b):
    assert a.shape[0] == b.shape[0] #same size and the zero is for just the number not a dtype
    n=b.shape[0]
    result = 0.0
    for i in range(n):
        result = result + a[i]*b[i]

    return result

In [92]:
#test this 
vector_vector_multiplication(u, v)

np.float64(14.0)

In [93]:
# this already exists in numpy so we can directly use 
u.dot(v)

np.int64(14)

In [107]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

In [108]:
v

array([1, 0, 0, 2])

In [109]:
# vectro mtrx mult
def matrix_vector_multiplication(A,b):
    assert A.shape[1] == b.shape[0]
    num_rows = A.shape[0]
    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(A[i],b)
    return result    

In [110]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [111]:
U.dot(v)

array([14,  5,  5])

In [112]:
V=np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])

In [125]:
# mtrx mtrx mult
def matrix_matrix_multiplication(A,B):
    assert A.shape[1] == B.shape[0]
    num_rows = A.shape[0]
    num_cols = B.shape[1]
    result = np.zeros((num_rows, num_cols))
    for i in range(num_cols):
        bi=B[:, i]
        Abi = matrix_vector_multiplication(A,bi)
        result[:, i] = Abi
    return result    

In [126]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [127]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [129]:
# identit matrx
I=np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [130]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [131]:
#computing the inverse, lets grab the first three rows of our matreix so it is square
Vs = V[[0,1,2]]

In [132]:
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [133]:
Vs_inv = np.linalg.inv(Vs)

In [134]:
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [135]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [136]:
#this will be useful for linear regression we will see later.

In [137]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [144]:
df = pd.DataFrame(data, columns=columns)

In [145]:
df 

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [149]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [150]:
df['Make']

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [148]:
#put a list inside brackets
df[['Make', 'Model', 'MSRP']]

Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

In [151]:
# add another column called id
df['id'] = [1, 2, 3, 4, 5]

In [152]:
df['id']

0    1
1    2
2    3
3    4
4    5
Name: id, dtype: int64

In [153]:
df['id'] = [10, 20, 30, 40, 50]

In [154]:
# similar to dict we can use del oprator to delete a kolo
del df['id']

In [155]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [156]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [157]:
df.Make.index

RangeIndex(start=0, stop=5, step=1)

In [158]:
df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [159]:
df.loc[[1,2]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
1         Sedan  27150  
2   convertible  54990

In [162]:
# replace the index for example
df.index = ['a' ,'b' ,'c', 'd', 'e']

In [163]:
df.loc[[1,2]]

KeyError: "None of [Index([1, 2], dtype='int64')] are in the [index]"

In [164]:
df.loc[['b', 'e']]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
b         Sedan  27150  
e        Pickup  32340

In [165]:
# we can refer to a positinal index but sted of loc we do iloc and we still look for exactly the elements
df.iloc[[1, 2]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
b  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
b         Sedan  27150  
c   convertible  54990

In [166]:
# come back to our trad index in our table for our index but it keeps the old index
df.reset_index()

index     Make     Model  Year  Engine HP  Engine Cylinders  \
0     a   Nissan    Stanza  1991      138.0                 4   
1     b  Hyundai    Sonata  2017        NaN                 4   
2     c    Lotus     Elise  2010      218.0                 4   
3     d      GMC    Acadia  2017      194.0                 4   
4     e   Nissan  Frontier  2017      261.0                 6   

  Transmission Type Vehicle_Style   MSRP  
0            MANUAL         sedan   2000  
1         AUTOMATIC         Sedan  27150  
2            MANUAL   convertible  54990  
3         AUTOMATIC       4dr SUV  34450  
4            MANUAL        Pickup  32340

In [167]:
# notice it kept both indices, if we dont care for the abcde one just drop true it
df.reset_index(drop=True)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [168]:
# BE CAREFUL IT DIDNT CHANGE DF!!!!! (think deep vs shallow copy and all that jazz)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            MANUAL   
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   convertible  54990  
d       4dr SUV  34450  
e        Pickup  32340

In [170]:
# reassign to df to do that
df = df.reset_index(drop=True)

In [171]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340